##GROUPID-11 (17114008_17114010) AMAN JAISWAL & AMIT VISHWAKARMA 
##DATE 28 OCTOBER 2018
##assembly language generated by c compiler decToBCD.s

.file	1 ""
	.section .mdebug.abi32
	.previous
	.nan	legacy
	.module	fp=32
	.module	nooddspreg
	.abicalls
	.rdata
	.align	2
$LC0:
	.ascii	"%s\000"
	.align	2
$LC1:
	.ascii	"0000 \000"
	.align	2
$LC2:
	.ascii	"0001 \000"
	.align	2
$LC3:
	.ascii	"0010 \000"
	.align	2
$LC4:
	.ascii	"0011 \000"
	.align	2
$LC5:
	.ascii	"0100 \000"
	.align	2
$LC6:
	.ascii	"0101 \000"
	.align	2
$LC7:
	.ascii	"0110 \000"
	.align	2
$LC8:
	.ascii	"0111 \000"
	.align	2
$LC9:
	.ascii	"1000 \000"
	.align	2
$LC10:
	.ascii	"1001 \000"
	.text
	.align	2
	.globl	main
	.set	nomips16
	.set	nomicromips
	.ent	main
	.type	main, @function
main:
	.frame	$fp,104,$31		# vars= 72, regs= 2/0, args= 16, gp= 8
	.mask	0xc0000000,-4
	.fmask	0x00000000,0
	.set	noreorder
	.cpload	$25
	.set	nomacro
	addiu	$sp,$sp,-104
	sw	$31,100($sp)
	sw	$fp,96($sp)
	move	$fp,$sp
	.cprestore	16
	movz	$31,$31,$0
	addiu	$2,$fp,36
	move	$5,$2
	lw	$2,%got($LC0)($28)
	nop
	addiu	$4,$2,%lo($LC0)
	lw	$2,%call16(__isoc99_scanf)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,__isoc99_scanf
1:	jalr	$25
	nop

	lw	$28,16($fp)
	addiu	$2,$fp,36
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	sw	$2,28($fp)
	sb	$0,48($fp)
	sw	$0,24($fp)
	b	$L2
	nop

$L16:
	lw	$2,24($fp)
	addiu	$3,$fp,24
	addu	$2,$3,$2
	lbu	$2,12($2)
	nop
	sb	$2,32($fp)
	lb	$2,32($fp)
	nop
	addiu	$2,$2,-48
	sltu	$3,$2,10
	beq	$3,$0,$L3
	nop

	sll	$3,$2,2
	lw	$2,%got($L5)($28)
	nop
	addiu	$2,$2,%lo($L5)
	addu	$2,$3,$2
	lw	$2,0($2)
	nop
	addu	$2,$2,$28
	j	$2
	nop

	.rdata
	.align	2
	.align	2
$L5:
	.gpword	$L4
	.gpword	$L6
	.gpword	$L7
	.gpword	$L8
	.gpword	$L9
	.gpword	$L10
	.gpword	$L11
	.gpword	$L12
	.gpword	$L13
	.gpword	$L14
	.text
$L4:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC1)($28)
	nop
	lw	$4,%lo($LC1)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC1)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L6:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC2)($28)
	nop
	lw	$4,%lo($LC2)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC2)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L7:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC3)($28)
	nop
	lw	$4,%lo($LC3)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC3)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L8:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC4)($28)
	nop
	lw	$4,%lo($LC4)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC4)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L9:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC5)($28)
	nop
	lw	$4,%lo($LC5)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC5)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L10:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC6)($28)
	nop
	lw	$4,%lo($LC6)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC6)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L11:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC7)($28)
	nop
	lw	$4,%lo($LC7)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC7)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L12:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC8)($28)
	nop
	lw	$4,%lo($LC8)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC8)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L13:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC9)($28)
	nop
	lw	$4,%lo($LC9)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC9)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L14:
	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(strlen)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strlen
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$3,$2
	addiu	$2,$fp,48
	addu	$2,$2,$3
	lw	$3,%got($LC10)($28)
	nop
	lw	$4,%lo($LC10)($3)
	nop
	swl	$4,0($2)
	swr	$4,3($2)
	addiu	$3,$3,%lo($LC10)
	lbu	$4,4($3)
	nop
	sb	$4,4($2)
	lbu	$3,5($3)
	nop
	sb	$3,5($2)
	b	$L15
	nop

$L3:
	lb	$2,32($fp)
	nop
	move	$3,$2
	addiu	$2,$fp,48
	move	$5,$3
	move	$4,$2
	lw	$2,%call16(strcat)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,strcat
1:	jalr	$25
	nop

	lw	$28,16($fp)
	nop
$L15:
	lw	$2,24($fp)
	nop
	addiu	$2,$2,1
	sw	$2,24($fp)
$L2:
	lw	$3,24($fp)
	lw	$2,28($fp)
	nop
	slt	$2,$3,$2
	bne	$2,$0,$L16
	nop

	addiu	$2,$fp,48
	move	$4,$2
	lw	$2,%call16(puts)($28)
	nop
	move	$25,$2
	.reloc	1f,R_MIPS_JALR,puts
1:	jalr	$25
	nop

	lw	$28,16($fp)
	move	$2,$0
	move	$sp,$fp
	lw	$31,100($sp)
	lw	$fp,96($sp)
	addiu	$sp,$sp,104
	j	$31
	nop

	.set	macro
	.set	reorder
	.end	main
	.size	main, .-main
	.ident	"GCC: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609"